from pydantic import BaseModel, Field
from typing import List, Dict
from time import time

class ChatRequest(BaseModel):
    message: str = Field(..., description="The user's message to the chat model")

class ChatResponse(BaseModel):
    answer: str = Field(description="The answer generated by the model")
    #timestamp: time = Field(default_factory=time, description="The time the response was generated")
    